name:                Dr Daniel Nemenyi
title:               Daniel Nemenyi
url:                 https://danielnemenyi.net
enforce_ssl:         danielnemenyi.net
baseurl:             ""
include:             ['_pages']
exclude:             ['_includes/notes_graph.json']

permalink:           /blog/:slug
relative_permalinks: false

plugins:
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-sitemap

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /notes/:path
  bookshelf:
    output: true
    permalink: /bookshelf/:path

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "_bookshelf/**/*.md"
    values:
      layout: "bookshelf"
